### ISSUE TITLE
.deb package is missing some dependencies

### ISSUE THREAD

**Issue by adityapk00** [ZcashFoundation/zepio#128]
The `.deb` is missing the `libappindicator1` dependency. 

```
adityapk@t3 ~/Downloads> sudo dpkg -i zepio-linux-v0.7.0.deb 
Selecting previously unselected package zepio.
(Reading database ... 272462 files and directories currently installed.)
Preparing to unpack zepio-linux-v0.7.0.deb ...
Unpacking zepio (0.7.0) ...
dpkg: dependency problems prevent configuration of zepio:
 zepio depends on libappindicator1; however:
  Package libappindicator1 is not installed.
```

After I manually installed the package, it worked. Maybe add it as a dependency in the `.deb` file?

**Comment by andrerfneves** [comment]
Thanks @adityapk00, going to debug this further.

**Comment by georgelima** [comment]
Weird because `electron-builder` already installs this dependency by default, anyway I'll explicitly define there, let's see if works

Ps.: https://www.electron.build/configuration/linux#debian-package-options

**Comment by andrerfneves** [comment]
Resolved here: https://github.com/ZcashFoundation/zepio/pull/132

**Comment by andrerfneves** [comment]
Released here https://github.com/ZcashFoundation/zepio/releases/tag/v0.7.1
