### ISSUE TITLE
Where is the public key for signing releases?

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zepio#129]
It might be handy to link to it in the ['Verifying...'](https://zepiowallet.com/installation#verifying-the-download) section of the docs, as well as some instructions about using gpg to verify (copy-pasting the instructions from the [codesign README](https://github.com/adityapk00/codesign#verifying-signatures) would be great).

**Comment by garethtdavies** [comment]
There's also an example here that can be easily modified https://docs.zecwallet.co/installation/#signatures

**Comment by andrerfneves** [comment]
We'll be sure to add those into the docs as well as the README. Thanks @dconnolly and @garethtdavies!

**Comment by andrerfneves** [comment]
Pubkey added https://github.com/ZcashFoundation/zepio/pull/141

**Comment by andrerfneves** [comment]
Resolved
