### ISSUE TITLE
Default custom fee values

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zepio#130]
![zepio-send-customfee](https://user-images.githubusercontent.com/135382/58587996-85113e00-8213-11e9-91ac-17b90f107967.png)

The custom fee default values are an order of magnitude higher than the default network fee of 0.0001 ZEC.  Having a fee that is 10x the default fee marked as *Low* is somewhat confusing.

**Comment by andrerfneves** [comment]
Resolved here: https://github.com/ZcashFoundation/zepio/pull/133

**Comment by andrerfneves** [comment]
Released here https://github.com/ZcashFoundation/zepio/releases/tag/v0.7.1
