### ISSUE TITLE
Zepio could not find a daemon running, please check the logs

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zepio#131]
![zepio-bug](https://user-images.githubusercontent.com/135382/58589483-d66efc80-8216-11e9-9b7c-b0ad33c3d715.png)

As reported here: https://forum.zcashcommunity.com/t/introducing-zepio-wallet/33644 this error is displayed when launching Zepio. As per that forum thread various debugging options have been tried such as removing the params dir and also renaming any existing .zcash directory. 

I can confirm it works when connecting to an external zcashd so it looks like it is not detecting that it needs to start the embedded zcashd for some reason.

```
{"error":false,"status":"Downloading network params, this may take some time depending on your connection speed"}
Fetching params
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.

{"error":false,"status":"Zepio Starting"}
Already is running!
```

**Comment by andrerfneves** [comment]
Thanks @garethtdavies for the detailed info. Looking into it and hoping to push fixes asap

**Comment by garethtdavies** [comment]
Debugging on my machine and I think the issue is with the `process-exists`. I was running a Docker container with Insight explorer running so:

```
ps -aux | grep zcashd
gareth   13093  0.0  0.0   8856   856 pts/0    S+   07:34   0:00 grep --color=auto zcashd
gareth   21466  0.4  3.4 4262572 2257288 pts/0 SLl+ May29   3:15 /home/zcashd/zcash-patched-for-explorer/src/zcashd --conf=/home/zcashd/.zcash/zcash.conf --datadir=/home/zcashd/.zcash
```

I'm guessing it is detecting that second process. To test I stopped the container:

```
ps -aux | grep zcashd
gareth   13987  0.0  0.0   8856   912 pts/0    S+   07:35   0:00 grep --color=auto zcashd
```

and now it works. Not sure how ZecWallet handles it as I'm able to open that while also running containers.

**Comment by garethtdavies** [comment]
From the same author so I guess this is a common issue :smile:  https://github.com/sindresorhus/is-docker

**Comment by andrerfneves** [comment]
@garethtdavies amazing. Love finding similar bugs to piggy-back on solutions with!

**Comment by garethtdavies** [comment]
There is of course a legitimate use case of running zcashd in a container and exposing the RPC port so Zepio could communicate with it which I’m guessing won’t work if it starts the internal zcashd if that Docker fix is implemented and it doesn’t detect a local process?

**Comment by andrerfneves** [comment]
@garethtdavies can you try https://github.com/ZcashFoundation/zepio/releases/tag/v0.7.2?

**Comment by garethtdavies** [comment]
@andrerfneves It works :smile: 

```
{"error":false,"status":"Downloading network params, this may take some time depending on your connection speed"}
Fetching params
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.

{"error":false,"status":"Zepio Starting"}
Searching for zcashd.pid
Zepio couldn't find a `zcashd.pid`, that means there is no instance of zcash running on the machine, trying start built-in daemon
Zcash Daemon running. PID: 2939
```

**Comment by andrerfneves** [comment]
@garethtdavies glad to hear!
