### ISSUE TITLE
re-size the width of the App

### ISSUE THREAD

**Issue by IAbda** [ZcashFoundation/zepio#142]
When I re-size the width of the App, the content inside does not adjust accordingly.
I am running the Windows version of Zepio.

**Comment by andrerfneves** [comment]
@IAbda please provide screenshots as well as screen size so we can try and reproduce

**Comment by IAbda** [comment]
![Resize_Not_Adjusting_ZepioWallet](https://user-images.githubusercontent.com/16349565/58729687-60bb8a00-83ea-11e9-93ba-d724e3a37de6.png)
![Default_Size_ZepioWallet](https://user-images.githubusercontent.com/16349565/58729688-60bb8a00-83ea-11e9-9c4e-442c5ad91848.png)

**Comment by IAbda** [comment]
Looks like this issue happens in Dashboard view only.

**Comment by andrerfneves** [comment]
Resolved here: https://github.com/ZcashFoundation/zepio/pull/147
