### ISSUE TITLE
ui has no respond after importing private key, only showing 'loading'

### ISSUE THREAD

**Issue by lixujasonFengXing** [ZcashFoundation/zepio#143]
ui has no response after importing private key, only showing 'loading'.

**Comment by andrerfneves** [comment]
@lixujasonFengXing can you provide some ways for us to reproduce this? It's been working well on our side. What Zepio version are you using? OS and version as well would be helpful.

**Comment by lixujasonFengXing** [comment]
v0.7.2 , mac os

**Comment by lixujasonFengXing** [comment]
importing private key function is quite tricky as i encountered similar issue in zecwallet https://github.com/ZcashFoundation/zecwallet/issues/137
