### ISSUE TITLE
blank dropdown list after goto ‘Send’ page for the first time

### ISSUE THREAD

**Issue by lixujasonFengXing** [ZcashFoundation/zepio#144]
After interacting with ui for a while, the dropdown list would have the address options

**Comment by lixujasonFengXing** [comment]
balances are all 0, which means it does not show balance correctly.

**Comment by andrerfneves** [comment]
So you have ZEC in your addresses, but they don't show in the dropdown? Can you submit specs and versions so we can try and debug?

**Comment by lixujasonFengXing** [comment]
v0.7.2, mac os

**Comment by lixujasonFengXing** [comment]
<img width="1132" alt="dropdown list issue" src="https://user-images.githubusercontent.com/3069265/58749082-c4f65080-84b3-11e9-8fcf-cee05ff6baa9.png">

**Comment by lixujasonFengXing** [comment]
Everytime restarting the mac os v0.7.2 app，goto ‘send’ page，the dropdown list is empty，but the problem would disappear after a while.

**Comment by andrerfneves** [comment]
Resolved in v0.7.3
