### ISSUE TITLE
FileRepMalware [PUP] detected by AVAST in Windows exec

### ISSUE THREAD

**Issue by DurinDwarf** [ZcashFoundation/zepio#149]
As described in the title. AVAST antivirus detects a malware in the installer.

**Comment by andrerfneves** [comment]
Any screenshots, logs, anything of that nature we can look to understand? I'd guess AVAST is throwing an alert because of a dependency we might have in the app. If you could help debug that'd be great.

**Comment by andrerfneves** [comment]
Closing this for now. Let us know if you can give more information on this and we'll gladly reopen. Unable to reproduce at this point.
