### ISSUE TITLE
Transaction status cannot be copy and pasted

### ISSUE THREAD

**Issue by imichaelmiers** [ZcashFoundation/zepio#153]
When you make a shielded transaction , you get a transaction status popup confirming its been sent. The text in this with a txid etc cannot be copied to send to someone.

**Comment by andrerfneves** [comment]
@georgelima can we make it the TXID a clickable link?

**Comment by georgelima** [comment]
Done https://github.com/ZcashFoundation/zepio/pull/154. Please review there @andrerfneves

**Comment by andrerfneves** [comment]
@imichaelmiers will be published on next release v0.7.4
