### ISSUE TITLE
Console doesn't show statistics

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zepio#155]
## Description

Console doesn't show statistics.

### Steps to reproduce

Click on Console tab.

### Expected result

Statistics should be shown.

### Actual result

Statistics are all zero.

![Screen Shot 2019-06-14 at 20 56 56](https://user-images.githubusercontent.com/227442/59529001-7bacf480-8ee8-11e9-9c98-04dff4a7caf8.png)

### Environment

- What version of Zepio are you using?
Latest develop branch.
- Which Operating System are you using (macOS/Linux/Windows)? What version?
macOS 10.13.6 (17G8018)
- Are you using an external `zcashd` daemon or the one built inside Zepio?
Built-in.

### Logs

There are no errors in the log.

**Comment by andrerfneves** [comment]
Resolved by #157. Will be on v0.7.4
