### ISSUE TITLE
blockchain from zecwallet

### ISSUE THREAD

**Issue by Walley303** [ZcashFoundation/zepio#160]
I downloaded the ZEC blockchain when first using ZecWallet and was wondering if I can just import all the .dat files into Zepio? If so, how? I would prefer not to have to download the whole blockchain all over again.

**Comment by andrerfneves** [comment]
Zepio should pick up your zcash configuration file and be able to read the same blockchain data. It should not redownload the data. Have you given it a try?

**Comment by Walley303** [comment]
Started Zepio, "Zepio Starting" for 15 minutes without seeming progress so quit.

**Comment by Walley303** [comment]
OK, resolved after I restarted the computer for another reason.

**Comment by andrerfneves** [comment]
Awesome. Glad to hear it works!
